# Getting into Array, List, Dict, Tuple

## List

In [1]:
x = [1, 2, 3, 'name', True]
print(x)

x[0] = 0;
print(x)


[1, 2, 3, 'name', True]
[0, 2, 3, 'name', True]


In [2]:
x2d =[[1,1,1], [2,2,2], ['x', 'x', 'x'] ] 
print(x2d)

x2d[1][1] = 0
print(x2d)


[[1, 1, 1], [2, 2, 2], ['x', 'x', 'x']]
[[1, 1, 1], [2, 0, 2], ['x', 'x', 'x']]


In [3]:
import numpy as np

x3d = np.ones((1,2,3))
print(x3d)

[[[1. 1. 1.]
  [1. 1. 1.]]]


Lets create a 3D - Array of

In [4]:
nLay = 10
nRow = 5
nCol = 8

ThreeDArray = np.ones((nLay, nRow, nCol))
ThreeDArray[nLay - 1][nRow - 1][nCol - 1] = 10
ThreeDArray[nLay - 1][nRow - 1] = 10
ThreeDArray[nLay - 1] = 10

ThreeDArray[-1, -1, -1] = -1
print(ThreeDArray)

[[[ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.

### Dictionary

Is a named list

In [5]:
phonebook = {
    'Andrew Parson':8806336, \
    'Emily Everett':6784346, \
    'Peter Power':7658344, \
    'Lewis Lame':1122345 \
}

print(phonebook)

{'Lewis Lame': 1122345, 'Peter Power': 7658344, 'Emily Everett': 6784346, 'Andrew Parson': 8806336}


### Tuple

Immutable List

In [6]:
months = ('January','February','March','April','May','June',\
'July','August','September','October','November','  December')

print(months)

('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', '  December')


In [7]:
months[0]='NewMonth'

TypeError: 'tuple' object does not support item assignment