# Flopy Paramater Estimation

Taken from https://github.com/modflowpy/flopy/blob/4f42638766d6a33cbc75f61a5193b787e68f4fe8/examples/Notebooks/flopy3_PEST.ipynb



This notebook demonstrates the current parameter estimation functionality that is available with FloPy. The capability to write a simple template file for PEST is the only capability implemented so far. The plan is to develop functionality for creating PEST instruction files as well as the PEST control file.

In [1]:
%matplotlib inline
import os
import sys
import numpy as np

# run installed version of flopy or add local path
try:
    import flopy
except:
    fpth = os.path.abspath(os.path.join('..', '..'))
    sys.path.append(fpth)
    import flopy

print(sys.version)
print('numpy version: {}'.format(np.__version__))
print('flopy version: {}'.format(flopy.__version__))

3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
numpy version: 1.14.5
flopy version: 3.2.9


This notebook will work with a simple model using the dimensions below

In [2]:
# Define the model dimensions
nlay = 3
nrow = 20
ncol = 20

# Create the flopy model object and add the dis and lpf packages
m = flopy.modflow.Modflow(modelname='mymodel', model_ws='./data')
dis = flopy.modflow.ModflowDis(m, nlay, nrow, ncol)
lpf = flopy.modflow.ModflowLpf(m, hk=10.)

### Simple One Parameter Example

In order to create a PEST template file, we first need to define a parameter. For example, let's say we want to parameterize hydraulic conductivity, which is a static variable in flopy and MODFLOW. As a first step, let's define a parameter called HK_LAYER_1 and assign it to all of layer 1. We will not parameterize hydraulic conductivity for layers 2 and 3 and instead leave HK at its value of 10. (as assigned in the block above this one). We can do this as follows.

In [3]:
mfpackage = 'lpf'
partype = 'hk'
parname = 'HK_LAYER_1'
idx = np.empty((nlay, nrow, ncol), dtype=np.bool)

idx[0] = True
idx[1:] = False

# The span variable defines how the parameter spans the package
span = {'idx': idx}

# These parameters have not affect yet, but may in the future
startvalue = 10.
lbound = 0.001
ubound = 1000.
transform='log'

pArray = []

pArray.append(flopy.pest.Params(mfpackage, partype, parname, startvalue, lbound, ubound, span))

mfpackage = 'lpf'
partype = 'hk'
parname = 'HK_LAYER_2'
idx = np.empty((nlay, nrow, ncol), dtype=np.bool)

idx[0] = False
idx[1] = True
idx[2] = False

# The span variable defines how the parameter spans the package
span = {'idx': idx}

# These parameters have not affect yet, but may in the future
startvalue = 100.
lbound = 0.01
ubound = 10000.
transform='log'

pArray.append(flopy.pest.Params(mfpackage, partype, parname, startvalue, lbound, ubound, span))

At this point, we have enough information to the write a PEST template file for the LPF package. We can do this using the following statement:

In [4]:
tw = flopy.pest.TemplateWriter(m, pArray)
tw.write_template()

The following packages will be parameterized: ['LPF']



At this point, the lpf template file will have been created. The following block will print the template file.

In [5]:
lines = open('./data/mymodel.lpf.tpl', 'r').readlines()
for l in lines:
    print(l.strip())

ptf ~
# LPF package for  MODFLOW-2005, generated by Flopy.
0    -1E+30         0
0         0         0
0         0         0
1.000000E+00   1.000000E+00   1.000000E+00
0         0         0
0         0         0
CONSTANT ~ HK_LAYER_1  ~    #hk Layer 1
CONSTANT    1.000000E+00                           #vka layer 1
CONSTANT ~ HK_LAYER_2  ~    #hk Layer 2
CONSTANT    1.000000E+00                           #vka layer 2
CONSTANT 10.0    #hk Layer 3
CONSTANT    1.000000E+00                           #vka layer 3


The span variable will also accept 'layers', in which the parameter applies to the list of layers, as shown next. When 'layers' is specifed in the span dictionary, then the original hk value of 10. remains in the array, and the multiplier is specified on the array control line.

In [6]:
mfpackage = 'lpf'
partype = 'hk'
parname = 'HK_LAYER_1-3'

# Span indicates that the hk parameter applies as a multiplier to layers 0 and 2 (MODFLOW layers 1 and 3)
span = {'layers': [0, 1]}

# These parameters have not affect yet, but may in the future
startvalue = 10.
lbound = 0.001
ubound = 1000.
transform='log'

p = flopy.pest.Params(mfpackage, partype, parname, startvalue,
                      lbound, ubound, span)
tw = flopy.pest.templatewriter.TemplateWriter(m, [p])
tw.write_template()

The following packages will be parameterized: ['LPF']



In [7]:
lines = open('./data/mymodel.lpf.tpl', 'r').readlines()
for l in lines:
    print(l.strip())

ptf ~
# LPF package for  MODFLOW-2005, generated by Flopy.
0    -1E+30         0
0         0         0
0         0         0
1.000000E+00   1.000000E+00   1.000000E+00
0         0         0
0         0         0
INTERNAL ~ HK_LAYER_1-3  ~ (FREE) -1      #hk Layer 1
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0      

### Multiple Parameter Zoned Approach


The params module has a helper function called zonearray2params that will take a zone array and some other information and create a list of parameters, which can then be passed to the template writer. This next example shows how to create a slightly more complicated LPF template file in which both HK and VKA are parameterized.

In [8]:
# Create a zone array
zonearray = np.ones((nlay, nrow, ncol), dtype=int)
zonearray[0, 10:, 7:] = 2
zonearray[0, 15:, 9:] = 3
zonearray[1] = 4

print(zonearray)

[[[1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  ...
  [1 1 1 ... 3 3 3]
  [1 1 1 ... 3 3 3]
  [1 1 1 ... 3 3 3]]

 [[4 4 4 ... 4 4 4]
  [4 4 4 ... 4 4 4]
  [4 4 4 ... 4 4 4]
  ...
  [4 4 4 ... 4 4 4]
  [4 4 4 ... 4 4 4]
  [4 4 4 ... 4 4 4]]

 [[1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]]


In [9]:
# Create a list of parameters for HK
mfpackage = 'lpf'
parzones = [2, 3, 4]
parvals = [56.777, 78.999, 99.]
lbound = 5
ubound = 500
transform = 'log'
plisthk = flopy.pest.zonearray2params(mfpackage, 'hk', parzones, lbound,
                                      ubound, parvals, transform, zonearray)

In this case, Flopy will create three parameters: hk_2, hk_3, and hk_4, which will apply to the horizontal hydraulic conductivity for cells in zones 2, 3, and 4, respectively. Only those zone numbers listed in parzones will be parameterized. For example, many cells in zonearray have a value of 1. Those cells will not be parameterized. Instead, their hydraulic conductivity values will remain fixed at the value that was specified when the Flopy LPF package was created.

In [10]:
# Create a list of parameters for VKA
parzones = [1, 2]
parvals = [0.001, 0.0005]
zonearray = np.ones((nlay, nrow, ncol), dtype=int)
zonearray[1] = 2
plistvk = flopy.pest.zonearray2params(mfpackage, 'vka', parzones, lbound,
                                      ubound, parvals, transform, zonearray)

In [11]:
# Combine the HK and VKA parameters together
plist = plisthk + plistvk
for p in plist:
    print(p.name, p.mfpackage, p.startvalue)

hk_2 lpf 56.777
hk_3 lpf 78.999
hk_4 lpf 99.0
vka_1 lpf 0.001
vka_2 lpf 0.0005


In [12]:
# Write the template file
tw = flopy.pest.templatewriter.TemplateWriter(m, plist)
tw.write_template()

The following packages will be parameterized: ['LPF']



In [13]:
# Print contents of template file
lines = open('./data/mymodel.lpf.tpl', 'r').readlines()
for l in lines:
    print(l.strip())


ptf ~
# LPF package for  MODFLOW-2005, generated by Flopy.
0    -1E+30         0
0         0         0
0         0         0
1.000000E+00   1.000000E+00   1.000000E+00
0         0         0
0         0         0
INTERNAL 1.0 (FREE) -1      #hk Layer 1
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0            10.0
10.